export const products = [
    {
        name: 'Nintendo Switch',
        brand: 'نینتندو',
        category: 'کنسول بازی',
        subCategory: '',
        feature: {},
        price: '۱۸،۳۲۰،۰۰۰',
        discountedPrice: '۱۷،۰۰۰،۰۰۰',
        quantity: 'کمتر از ۱ عدد باقی مانده',
        color: '',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1671909847/tech-shop/png/switch_img_l75xy3.png',
    },
    {
        name: 'Galaxy S22+',
        brand: 'سامسونگ',
        category: 'موبایل',
        subCategory: '',
        feature: {
            value: '۲۵۶',
            unit: 'گیگابایت',
        },
        price: '۴۵،۳۲۰،۰۰۰',
        discountedPrice: '۴۵،۰۰۰،۰۰۰',
        quantity: 'کمتر از ۲ عدد باقی مانده',
        color: 'سفید',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1669623988/tech-shop/png/samsung-rainbow-g0-sms906uzwv-phantom-white-hero-color-128-gb_copy_im6atf.png',
    },
    {
        name: 'Galaxy S21',
        brand: 'سامسونگ',
        category: 'موبایل',
        subCategory: '',
        feature: {
            value: '۲۵۶',
            unit: 'گیگابایت',
        },
        price: '۱۵،۰۰۰،۰۰۰',
        discountedPrice: '۱۲،۰۰۰،۰۰۰',
        quantity: '',
        color: 'خاکستری تیره',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1671919863/tech-shop/png/samsung-galaxy-s21-fe-pakistan-priceoye-6mxwx_zuz52q.png',
    },
    {
        name: 'xBox S series Controller',
        brand: 'مایکروسافت',
        category: 'کنترلر بازی',
        subCategory: '',
        feature: {},
        price: '۱۵،۰۰۰،۰۰۰',
        discountedPrice: '۱۲،۰۰۰،۰۰۰',
        quantity: '',
        color: 'سفید',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1671908765/tech-shop/png/e96370bf-ad68-4af8-82d6-2c980b75d0c0_gkqxum.png',
    },
    {
        name: 'iPhone 14 Pro Max',
        brand: 'اپل',
        category: 'موبایل',
        subCategory: '',
        feature: {
            value: '۲۵۶',
            unit: 'گیگابایت',
        },
        price: '۷۵،۵۲۰،۰۰۰',
        discountedPrice: '۷۴،۰۰۰،۰۰۰',
        quantity: 'کمتر از ۵ عدد باقی مانده',
        color: 'بنفش',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1671919649/tech-shop/png/003_aiph8z.png',
    },
    {
        name: 'Charger Stand With Cooling Fan',
        brand: 'مایکروسافت',
        category: 'لوازم جانبی بازی',
        subCategory: 'خنک‌کننده‌ی کنسول',
        feature: {},
        price: '۷۵،۵۲۰،۰۰۰',
        discountedPrice: '۷۴،۰۰۰،۰۰۰',
        quantity: 'کمتر از ۵ عدد باقی مانده',
        color: 'مشکی مات',
        photo: 'https://res.cloudinary.com/phase-1/image/upload/v1671907199/tech-shop/png/Charging_Stand_with_Cooling_Fan_CODOGOY_Vertical_Stand_Compatible_with_Xbox_Series_X_S_Console_and_Controller_Vertical_Dual_Controller_Charger_Station..._copy_b1n4x3.png',
    },
];